apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  DB_PASSWORD: "secretpassword"
  CLOUDFLARE_TUNNEL_TOKEN: "eyJhIjoiNTQ1MDQ4NWI0MWVmYWZiZWQ4OWVkNjg0NzhhN2I0ZmMiLCJ0IjoiYWEzYTA4MmQtOTUyNC00ZTU2LTg3YmYtMmQzNDFkMDgzY2I5IiwicyI6Ik9EWXpZVGRqWkRndE9XVmtaQzAwWkRZMExXRmhNamd0T1RWbFpUWTVNRFl3TkRoaCJ9"
